source 'https://cdn.cocoapods.org'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'composeApp', :path => '../composeApp'
#   pod 'shared', :path => '../shared'
  # Firebase pods
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # Add Google SignIn
  pod 'GoogleSignIn'
end